import { StyleSheet } from "react-native";

export const S = StyleSheet.create({
    // Layout
    flex1: { flex: 1 },
    row: { flexDirection: "row", alignItems: "center" },
    center: { justifyContent: "center", alignItems: "center" },

    // Header
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        shadowOpacity: 0.08,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
    },
    headerSide: { width: 64 },
    backBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        shadowOpacity: 0.12,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
    },
    headerTitle: {
        flex: 1,
        alignItems: "center",
        paddingVertical: 8,
    },
    titleText: {
        fontSize: 20,
        fontWeight: "700",
        textAlign: "center",
    },

    // List item
    itemContainer: {
        borderRadius: 16,
        padding: 16,
        marginVertical: 6,
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 1,
        shadowOpacity: 0.05,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
        elevation: 1,
    },
    itemIcon: {
        width: 48,
        height: 48,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    itemInfo: { flex: 1, marginLeft: 16, marginRight: 10 },
    itemName: { fontSize: 15, fontWeight: "600" },
    itemType: { fontSize: 12, marginTop: 3 },

    // Upload card
    uploadCard: {
        position: "absolute",
        bottom: 110,
        left: 16,
        right: 16,
        zIndex: 200,
        alignSelf: "center",
    },
    uploadRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    uploadTitle: { fontWeight: "700" },
    uploadPct: { fontWeight: "600" },
    cancelBtn: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 999,
        borderWidth: 1,
        marginTop: 8,
        alignSelf: "flex-end",
    },
    cancelText: { fontWeight: "600", fontSize: 12 },

    // FAB
    fabContainer: {
        position: "absolute",
        right: 16,
        alignItems: "center",
    },
    fabMenu: { marginBottom: 16, gap: 12 },
    fabSecondary: {
        width: 56,
        height: 56,
        borderRadius: 28,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: "#E5E7EB",
        shadowOpacity: 0.12,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 3 },
        elevation: 4,
    },
    fabMain: {
        width: 64,
        height: 64,
        borderRadius: 32,
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.25,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 6,
    },

    // Modals
    overlay: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0,0,0,0.45)",
    },
    modalBox: {
        width: "82%",
        padding: 24,
        borderRadius: 20,
        shadowOpacity: 0.2,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 8 },
        elevation: 8,
    },
    modalTitle: {
        fontSize: 17,
        fontWeight: "600",
        textAlign: "center",
        marginBottom: 16,
    },
    input: {
        borderWidth: 1,
        borderRadius: 12,
        padding: 12,
        fontSize: 15,
        marginBottom: 12,
    },
    btnRow: { flexDirection: "row", gap: 10 },
    btnPrimary: {
        flex: 1,
        padding: 12,
        borderRadius: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        backgroundColor: "#2563EB",
    },
    btnDanger: {
        flex: 1,
        padding: 12,
        borderRadius: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        backgroundColor: "#DC2626",
    },
    btnSecondaryBlue: {
        flex: 1,
        padding: 12,
        borderRadius: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        backgroundColor: "#DBEAFE",
    },
    btnSecondaryRed: {
        flex: 1,
        padding: 12,
        borderRadius: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        backgroundColor: "#FEE2E2",
    },
    btnTextWhite: { color: "#fff", fontWeight: "600", fontSize: 14 },
    btnTextBlue: { color: "#1D4ED8", fontWeight: "600", fontSize: 14 },
    btnTextRed: { color: "#B91C1C", fontWeight: "600", fontSize: 14 },
});
